### ISSUE TITLE
Update to CKAN 2.9.x

### ISSUE THREAD

**Issue by etj** [geosolutions-it/ckanext-dcatapit#254]
- [x] port to python 3
- [x] port to CKAN 2.9
- [x] Update of the CSW harvester for RNDT2 compatiblity

This extension depends on other CKAN extension:
- extensions already migrated to python3/ckan2.9
  - https://github.com/ckan/ckanext-dcat
  - https://github.com/ckan/ckanext-harvest
- extension to be migrated
  - [x] multilang (https://github.com/geosolutions-it/ckanext-multilang/issues/29)
- extension not yet migrated (start investigation, synch with community)
  - [x] spatial https://github.com/ckan/ckanext-spatial

**Comment by etj** [comment]
We need a final test with a flow like that:
- CKAN instance harvests a CSW entrypoint (e.g.: http://www.opendatanetwork.it/geonetwork/srv/ita/csw)
  - needed extensions `ckanext-harvest`, `ckanext-spatial`
- CKAN can be queried for harvested records in DCATAPIT format
  - needed extensions `ckanext-dcat`, `ckanext-dcatapit`, `ckanext-multilang`

**Comment by laza81** [comment]
Hi! There are any progress in this ? How is possible to replace this command:

`paster --plugin=ckanext-dcatapit vocabulary initdb --config=/etc/ckan/default/ckan.ini`

with this 

`ckan --config=/etc/ckan/default/ckan.ini dcatapit vocabulary initdb` 

inside venv, with CKAN 2.9.4 and Python3 ?

Thanks
